version: '3'

services:
  service:
    build: .
    ports:
      - 8080:8080 
    restart: always
    depends_on:
      - database
    # networks:
    #   - fullstack

  database:
    container_name: database
    image: mysql
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: service-db
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
#     networks:
#       - fullstack

# networks:
#   fullstack:
#     driver: bridge